### ISSUE TITLE
Error on install 

### ISSUE THREAD

**Issue by battosai30** [OpenSourcePolitics/decidim-module-navbar_links#4] opened 2020-06-26 11:30 UTC
Hi,

When I install navbar_links I get this error :

```
Fetching https://github.com/OpenSourcePolitics/decidim-module-navbar_links
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "decidim-core":
  In Gemfile:
    decidim-dev (= 0.21.0) was resolved to 0.21.0, which depends on
      decidim (= 0.21.0) was resolved to 0.21.0, which depends on
        decidim-core (= 0.21.0)

    decidim-navbar_links was resolved to 0.20.0, which depends on
      decidim-core (= 0.20.0)
```

Thanks for your work !

**Comment by battosai30** [comment] 2020-06-26 12:05
Ok I found a workaround : 

In Gemfile I change the requirement 
`gem 'decidim-navbar_links', git: "https://github.com/OpenSourcePolitics/decidim-module-navbar_links", branch: '0.21.0'`

**Comment by AL-HAYALI** [comment] 2020-12-05 19:26
@battosai30  I faced the same issue, I have used same your method but the didn't work because the branch: '0.21.0' is not exists.
I have tried with one of the previous branches but still getting the same error.
I'm facing problems with many gems and most of them aren't working Lol..
I keep asking questions in github and no one answer me.

**Comment by battosai30** [comment] 2020-12-07 08:21
Hi,

Strange, 0.21.0 is available : https://github.com/OpenSourcePolitics/decidim-module-navbar_links/tree/0.21.0
You can try with others branches : 0.22-stable, 0.21-stable ...

But if you have other problems with Ruby & co, I guess it's more a Ruby installation issue than a Decidim one.

**Comment by AL-HAYALI** [comment] 2020-12-08 20:32
@battosai30, thanks mate, I always follow the instructions but always let me down, tried to work with docker but due to thr lack of experience I couldn't reach the internal network of the container, the explanation in the github are really limited, especially the one provided for docker.
There is no one explaining in a video or a special youtube channel for that.

**Comment by battosai30** [comment] 2020-12-09 13:30
What is your operating system ?

**Comment by armandfardeau** [comment] 2020-12-10 10:35
Hello is your problem still present?

**Comment by AL-HAYALI** [comment] 2020-12-26 16:12
Hello @armandfardeau , Yes, still facing the same error:
I have used the following in my Gem file:
gem 'decidim-navbar_links', git: "https://github.com/OpenSourcePolitics/decidim-module-navbar_links", branch: '0.21.0'

Getting the following Error
''''''''''''''''''''''''''''''''''''''''''''''''''''''  Error   ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Bundler could not find compatible versions for gem "decidim-core":
  In snapshot (Gemfile.lock):
    decidim-core (= 0.23.1)

  In Gemfile:
    decidim-dev (= 0.23.1) was resolved to 0.23.1, which depends on
      decidim (= 0.23.1) was resolved to 0.23.1, which depends on
        decidim-core (= 0.23.1)

    decidim-navbar_links was resolved to 0.21.0, which depends on
      decidim-core (= 0.21.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
'''''''''''''''''''''''''''''''''''''''''''''''''''''  Error   ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Also, I have tried bundle update and got the same error

**Comment by AL-HAYALI** [comment] 2020-12-26 16:34
@armandfardeau , When I try :
gem 'decidim-navbar_links', git: "https://github.com/OpenSourcePolitics/decidim-module-navbar_links.git"
in my gem file I get this error:
"""""""""""""""""""""""""""""""""  Error  """""""""""""""""""""""""""""""""""""""""""""
Bundler could not find compatible versions for gem "decidim-core":
  In snapshot (Gemfile.lock):
    decidim-core (= 0.23.1)

  In Gemfile:
    decidim-dev (= 0.23.1) was resolved to 0.23.1, which depends on
      decidim (= 0.23.1) was resolved to 0.23.1, which depends on
        decidim-core (= 0.23.1)

    decidim-navbar_links was resolved to 0.24.0.dev, which depends on
      decidim-core (= 0.24.0.dev)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
"""""""""""""""""""""""""""""""""  Error  """""""""""""""""""""""""""""""""""""""""""""
it's been 3 weeks I'm struggling with that thing.

**Comment by armandfardeau** [comment] 2021-01-06 15:41
Could you share your repository? I wanna try to reproduce.

**Comment by AL-HAYALI** [comment] 2021-01-06 17:00
@armandfardeau Here is it:
https://github.com/MohammedSalahadin/Badragaz-Taminatal

Keeping in mind I have commented out the navbar gem in order to not face any error.

**Comment by armandfardeau** [comment] 2021-01-06 18:49
As you are using decidim version 0.23, you must use:
gem "decidim-navbar_links", git: "https://github.com/OpenSourcePolitics/decidim-module-navbar_links", branch: "0.23-stable"

Check put the following PR:
https://github.com/MohammedSalahadin/Badragaz-Taminatal/pull/1

Also, you don't need to include others decidim gem as core, or proposals as it's already in the gem.
Consider adding application.yml to gitgnore to avoid secrets divulgations

**Comment by AL-HAYALI** [comment] 2021-01-06 19:48
@armandfardeau Already merged the pull request, also added the application.yml to .gitignore Thank you brother, Apricate your help and effort..
Best Regards...

**Comment by armandfardeau** [comment] 2021-01-06 19:49
Glad you found a solution to your problem!

**Closed as completed by armandfardeau** 2021-01-06 19:49 UTC
Labels: triage
